version: '3.8'

services:
  # NestJS Backend - Production  
  backend:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile.prod
    container_name: logen-backend-quick
    environment:
      NODE_ENV: production
      DB_HOST: 162.55.213.90
      DB_PORT: 5433
      DB_USERNAME: locod_user
      DB_PASSWORD: locod_pass_2024
      DB_DATABASE: locod_db
      DB_SSL: "false"
      JWT_SECRET: logen_jwt_secret_production_2024_secure_key_v2
      JWT_EXPIRES_IN: 24h
      PORT: 7600
    ports:
      - "7600:7600"
    restart: unless-stopped

  # Next.js Frontend - Production
  frontend:
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile.prod
    container_name: logen-frontend-quick
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://162.55.213.90:7600
      PORT: 7601
    ports:
      - "7601:7601"
    depends_on:
      - backend
    restart: unless-stopped