/**
 * Loader de configuration pour le template
 * Charge la configuration injectée dynamiquement
 */

import { applyAutoNavbarColors } from '../utils/colorUtils.js';

let siteConfig = null;

/**
 * Charge la configuration du site de manière synchrone
 * @returns {Object} Configuration complète du site
 */
export const loadSiteConfig = () => {
  try {
    // 1. TOUJOURS vérifier d'abord la config injectée dans window.SITE_CONFIG
    // Cela permet de détecter les mises à jour de configuration
    if (typeof window !== 'undefined' && window.SITE_CONFIG) {
      siteConfig = processConfig(window.SITE_CONFIG);
      return siteConfig;
    }

    // 2. Si pas de config injectée, utiliser le cache s'il existe
    if (siteConfig) {
      return siteConfig;
    }

    // 3. Sinon essayer localStorage (pour les mises à jour dynamiques)
    const localConfig = localStorage.getItem('siteConfig');
    if (localConfig) {
      siteConfig = processConfig(JSON.parse(localConfig));
      return siteConfig;
    }

    // 4. En dernier recours, charger depuis /config.json
    loadConfigAsync();
    return processConfig(getFallbackConfig());
  } catch (error) {
    console.warn('Site configuration not found, using fallback:', error);
    return processConfig(getFallbackConfig());
  }
};

/**
 * Traite la configuration pour appliquer les améliorations automatiques
 * @param {Object} config - Configuration brute
 * @returns {Object} Configuration traitée
 */
const processConfig = (config) => {
  // 🎨 NOUVEAUTÉ : Application automatique des couleurs navbar
  if (!config.navbar?._autoGenerated) {
    config = applyAutoNavbarColors(config);
  }
  
  return config;
};

/**
 * Charge la configuration depuis /config.json de manière asynchrone
 */
const loadConfigAsync = async () => {
  if (siteConfig) return siteConfig;

  try {
    const response = await fetch('/config.json');
    if (response.ok) {
      const config = await response.json();
      siteConfig = processConfig(config);
      // Sauvegarder pour les accès futurs
      localStorage.setItem('siteConfig', JSON.stringify(siteConfig));
      
      // Forcer un re-render en émettant un événement
      window.dispatchEvent(new CustomEvent('configLoaded', { detail: siteConfig }));
      
      return siteConfig;
    }
  } catch (error) {
    console.warn('Failed to load config.json:', error);
  }
  
  return processConfig(getFallbackConfig());
};

/**
 * Force le rechargement de la configuration
 * Utile pour le développement et les mises à jour
 */
export const reloadSiteConfig = () => {
  siteConfig = null;
  localStorage.removeItem('siteConfig');
  return loadSiteConfig();
};

/**
 * Configuration de fallback (défaut Locod.AI)
 * Utilisée si aucune config n'est injectée
 */
const getFallbackConfig = () => {
  return {
    meta: {
      siteId: 'fallback',
      domain: 'localhost:3000',
      language: 'fr'
    },
    brand: {
      name: 'Locod.AI',
      slogan: 'Automatisez! Vite. Bien. Sans coder.',
      logo: 'logo-locodai.png',
      colors: {
        primary: '#3B82F6',
        secondary: '#8B5CF6',
        accent: '#06B6D4'
      }
    },
    content: {
      hero: {
        title: 'Template de développement',
        subtitle: 'Configuration requise',
        description: 'Veuillez injecter une configuration pour voir le site personnalisé.',
        cta: {
          primary: 'Configuration requise',
          secondary: 'Nous contacter'
        }
      },
      services: [
        {
          title: "Service exemple",
          description: "Configuration non chargée",
          icon: "default"
        }
      ],
      about: {
        title: 'Mode développement',
        description: 'Veuillez injecter une configuration pour voir le site personnalisé.'
      }
    },
    contact: {
      email: 'dev@template.local',
      phone: '+33 X XX XX XX XX',
      address: {
        city: 'Ville',
        country: 'Pays'
      }
    },
    features: {
      blog: false,
      testimonials: false,
      faq: false,
      newsletter: false,
      darkMode: true
    }
  };
};

/**
 * Utilitaire pour obtenir une couleur du thème
 * @param {string} colorKey - Clé de la couleur (primary, secondary, accent)
 * @returns {string} Couleur hexadécimale
 */
export const getThemeColor = (colorKey) => {
  const config = loadSiteConfig();
  return config.brand?.colors?.[colorKey] || '#3B82F6';
};

/**
 * Vérifie si une fonctionnalité est activée
 * @param {string} featureKey - Clé de la fonctionnalité
 * @returns {boolean}
 */
export const isFeatureEnabled = (featureKey) => {
  const config = loadSiteConfig();
  return config.features?.[featureKey] === true;
};

// Debug info
if (typeof window !== 'undefined') {
  console.log('🔧 Config loader initialized');
  if (window.SITE_CONFIG) {
    console.log('✅ Inline config found:', window.SITE_CONFIG.brand?.name);
  } else {
    console.log('⚠️ No inline config, will try async loading');
  }
}

export default loadSiteConfig;