name: Validate Template

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-template:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Make scripts executable
      run: chmod +x scripts/*.sh
      
    - name: Validate Iteration 2
      run: ./scripts/validate-iteration2.sh
      
    - name: Test Iteration 3
      run: ./scripts/test-iteration3.sh
      
    - name: Final validation
      run: ./scripts/validate-final.sh
      
    - name: Archive generated sites
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: generated-sites
        path: test-generation-final/